### ISSUE TITLE
Write extractor(s) for NDVI and PRI data

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#150]
### Description

Extract NDVI and PRI values, and % reflectance from xml files in ndviSensor and priSensor and insert into geostreams API.
### TODO:
- [x] Determine any dependencies
- [x] Extract values from .bin files (these are actually xml, see below)
- [ ] Check if time and location are in sync for two sensors (if so, records can be combined)
- [x] write extractor to convert files with geospatial, time, reflectances and NDVI / PRI values to geostreams API
- [x] document 
- [ ] write test.sh to work on sample data and compare to sample output
### Suggestions

These data, where each record has a time, point location, and then a few data points are similar to the data stream from the pheno tractor. If we can take these both and insert them into the geostreams database, then we will have combined five sensors into one format. From that point it should be easy to write extractors that summarize plot (or any polygon) data from these sensors, and the database already has mapping and plotting features within Clowder.

This is what I am thinking - does this make sense from the Clowder and data stream standardization perspective @robkooper @max-zilla ? Does this make sense in general, and with respect to these datasets @Mamatemenrs, @remotesensinglab ?

![image](https://cloud.githubusercontent.com/assets/464871/19782328/fa658d22-9c52-11e6-8551-d5dc324f2d7c.png)
### Appendix

This is a subtask of #64 
#### NDVI format

``` xml
<LemnaTecData>
    <Entry name="NDVI" value="0.803190499146552" unit="-" />
    <Entry name="Channel1TOP633" value="233.078997755" unit="umol/m^2/s" />
    <Entry name="Channel4TOP800" value="221.7064438158" unit="umol/m^2/s" />
    <Entry name="Channel1DOWN633" value="3.6708662746" unit="umol/SR/m^2/s" />
    <Entry name="Channel4DOWN800" value="31.9918451094" unit="umol/SR/m^2/s" />
</LemnaTecData>
```
#### PRI example

``` xml
<LemnaTecData>
    <Entry name="NDVI" value="0.047458169870772" unit="-" />
    <Entry name="Channel1TOP531" value="68.817235498" unit="umol/m^2/s" />
    <Entry name="Channel4TOP569" value="65.0497152665" unit="umol/m^2/s" />
    <Entry name="Channel1DOWN531" value="1.1867427872" unit="umol/SR /m^2/s" />
    <Entry name="Channel4DOWN569" value="1.2335518543" unit="umol/SR /m^2/s" />
</LemnaTecData>
```

**Comment by dlebauer** [comment]
According to specs, there is one NDVI sensor pointing up, one pointing down: 
@terraref/lemnatec could you please confirm?

**Comment by rachelshekar** [comment]
@dlebauer - is this a priority for the V0 release?

**Comment by dlebauer** [comment]
Yes

**Comment by rachelshekar** [comment]
@ZongyangLi - can you please update this issue?

**Comment by ZongyangLi** [comment]
I look into bin files in `/raw_data/ndviSensor/` several weeks ago. The content in the bin file is like:

`<LemnaTecData>
    <Entry name="NDVI" value="0.486768492611564" unit="-" />
    <Entry name="Channel1TOP633" value="259.2523123703" unit="umol/m^2/s" />
    <Entry name="Channel4TOP800" value="230.8212727595" unit="umol/m^2/s" />
    <Entry name="Channel1DOWN633" value="8.0706465413" unit="umol/SR/m^2/s" />
    <Entry name="Channel4DOWN800" value="20.8157258431" unit="umol/SR/m^2/s" />
</LemnaTecData>`

In the matlab codes [GetNDVI.m](https://github.com/terraref/computing-pipeline/blob/master/scripts/NDVI/GetNDVI.m), it reads the source file and outputs NDVI value given from source file.

Could some give me some idea on:
1. How to create a png using these metadata.
2. Where can I find Vis and NIR information.
3. Is that NDVI value in the source file is the right NDVI value should be added into somewhere else.
4. Should I consider each meta file as a pixel to a geospatial creation?

**Comment by dlebauer** [comment]
@ZongyangLi I just realized that the .bin files are actually XML text and that this is not an imaging sensor. So it may not be appropriate to convert to an image. 

The most important value is NDVI. First step might be to extract x, y, NDVI for each observation and look at the points. Perhaps this should be inserted into the Clowder geostreams API as a first step.

@anfrench, @remotesensinglab do you have any suggestions? 

Should we retain the four values (2 up and 2 down for 633 and 800 nm) in addition to NDVI or convert these to %reflectances for each channel?

**Comment by remotesensinglab** [comment]
I do not think it is necessary! Just keep the % reflectance (two values), and NDVI.

**Comment by anfrench** [comment]
I dont know the instsrument, is this a ratioing algorithm: upwelling divided by downwelling? Unfortunate choice of sensor labels TOP and DOWN since Id think the TOP captures the downwelling radiation and the bottom sensor captures the reflected signal?? Would be good to relabel but I suspect not possible. In that case some note ought to be added to metadata to clarify which sensor is which. Otherwise, two reflectances + NDVI is ok as long as the upwelling and downwelling calibrations are checked periodically, they need to be.

**Comment by rachelshekar** [comment]
@Mamatemenrs and @remotesensinglab - please update this issue

**Comment by max-zilla** [comment]
if you have a python script, please upload to GitHub so we can review and prep extractor.

Here is the preferred repository for the script:
https://github.com/terraref/extractors-multispectral 
please let me know if you don't have access. Easiest way would just be to create your own branch and add the file, then create a pull request.

**Comment by Paheding** [comment]
For extracting NDVI or PRI values from a .bin files, a python script has been uploaded in a branch named "Create binFile_NDVI_Extractor" with a pull request.

**Comment by max-zilla** [comment]
@Paheding thanks for uploading, I will take a look at follow up.

**Comment by Paheding** [comment]
@max-zilla  The python script for extracting NDVI from .bin files can found in [here](https://github.com/Paheding/extractors-multispectral/blob/25c7fdefd3b38628c2efed73d36d20a1445ee838/binFile_NDVI_Extractor)
The code reads all .bin files from current directory, extracts the NDVI values, and saves the extracted values to  a .csv file automatically.

**Comment by max-zilla** [comment]
https://github.com/terraref/extractors-multispectral/pull/6/files

@Paheding I merged your PR and implemented the code into the extractor framework. I have not tested yet but you can see how this was done here.
- renamed your script to DirectoryExtractor.py to preserve it.
- terra_bin2csv.py is the extractor script with 3 components. this is configured to be notified whenever any .bin file is uploaded into Clowder
  - check_message checks metadata to see if the .bin file belongs to NDVI or PRI sensor
  - process_message reads the bytes into a CSV and uploads it to clowder
  - init just adds a couple command line args
- batch_launcher and extractor_info are used in Clowder environment

I will try to make time to test before end of the week.

**Comment by Paheding** [comment]
Sounds good. Thanks.


Sidike Paheding (Patrick), Ph.D.
Postdoctoral Research Associate
Center for Sustainability
Saint Louis University

**Comment by max-zilla** [comment]
Quick update that this extractor is deployed to the VM and dependencies installed - as soon as @jdmaloney has the output directory mounted (so we can write outputs to Level_1 directory properly) I will start running.

**Comment by Paheding** [comment]
@max-zilla I installed pyClowder2 for extractor development, and ran the example_extractor named "wordcount.py".  It gives some error as follows:
![image](https://cloud.githubusercontent.com/assets/24866799/22529534/67b9b6f0-e89d-11e6-8d35-fc864165a6a6.png)
It seems there is a problem about connection. Any advice on this? Thanks.

**Comment by robkooper** [comment]
this looks like rabbitmq is not up and running. 

Did you install the docker images for rabbitmq and/or clowder?

**Comment by Paheding** [comment]
I installed docker and pyClowder 2. Not sure about docker images, is there
any document that I can look a look for installing the docker images?
Thanks.

--------------------
*Sidike Paheding, Ph.D.*
Postdoctoral Research Associate
Center for Sustainability
Saint Louis University
http://www.remotesensinglab.org/paheding.html

**Comment by Paheding** [comment]
@robkooper Yes, I installed them. Now when I ran the extractor named: wordcount.py, the extractor reports "Starting to listen for messages", so it seems working now. Thanks.

**Comment by robkooper** [comment]
if you upload a text image, does it work? On a mac you need to upload to http://youripaddresss:9000 and not to http://localhost:9000/

**Comment by Paheding** [comment]
@robkooper Not yet, could you provide steps to upload a text image? Thanks.
