### ISSUE TITLE
Write extractor for PSII camera

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#152]
### Description

Convert binary files to png thumbnail + netCDF raster data product. 

Code to read binary files and create a figure are in [`/scripts/PSII/GetPS2.m`](https://github.com/terraref/computing-pipeline/blob/master/scripts/PS2/GetPS2.m). These are written in Matlab / Octave.

Steps:
- [x] Determine any dependencies
- [x] Determine if it is easier to call an Octave script or re-write (e.g. in Python within extractor)
- [x] Replace code that uses GUI to select file so file can be passed as argument
- [ ] Replace figure generation step with writing out a png as thumbnail 
- [ ] Calibrate values to Temperature in degrees C
- [ ] Add geospatial attributes and metadata to file
- [ ] document 
- [ ] write test.sh to work on sample data and compare to sample output

This is a subtask of #64

**Comment by dlebauer** [comment]
There are a lot of files for each observation, 

* Picture taken before the flash (fdark to subtract background), then there is a flash, then a Fmin (F0 or Fmin) then a series of photos taken until Fmax.  
* Need to identify fdark, Fmin, and Fmax based on mean intensity
  * response curve to maximum fluorescence may be useful, but can be estimated later
* Calculate the photosynthetic efficiency = (fmax-fmin)/fmax.  
   * Subtract fdark from each value first. This is measure of photosynthetic efficiency.  However, you only want to look at plant material so you need to use segmentation.
  * ((fmax-fdark) - (fmin - fdark) /(fmax-fdark) = (fmax-fmin)/(fmax-fdark)

**Comment by dlebauer** [comment]
Here’s an example of data from the DDPSC system: http://plantcv.readthedocs.io/en/latest/psII_tutorial/

**Comment by dlebauer** [comment]
@nfahlgren can we use PlantCV for this directly, or perhaps after clipping to plot boundaries?

**Comment by nfahlgren** [comment]
@dlebauer good question, that actually might be pretty straightforward. I will take a look at some example data on Clowder and let you know

**Comment by nfahlgren** [comment]
I talked with @solmazhajmohammadi and figured out I was looking at images that lacked signal. I think I understand the structure of each snapshot now and looking at the data I believe we could definitely use the PlantCV tools we have for PSII data to process data from the scanner PSII camera. I can work up an extractor for this unless @ZongyangLi is working on it instead.

**Comment by dlebauer** [comment]
I think @ZongyangLi can work out the conversion from binary to image, but not the analysis of the response.

* Are you planning to compute in on time series on a per pixel basis, or on a per image basis? 
* do the images need to be subset to the plot scale? 

I suggested using netcdf in the issue description because this will speed up computing on time series (e.g. to calculate the values on a per-pixel basis) faster because a) it can be done in parallel and b) the file can be written to optimize extraction of time series.

**Comment by nfahlgren** [comment]
It looks like each snapshot is 101 images (Frames 0 - 100), a JSON metadata file, and an XML metadata file that contains the (presumably) Unix time of each frame. Based on my understanding of how the PSII system works at DDPSC, I think frame 0 is the F-dark image, taken before the light pulse, which can be used to remove background signal from the other frames. Frame 1 should be the first image taken after the light pulse, so it's the minimal fluorescence image (F-min or F0). Each successive frame can be used to measure the response of PSII to the light pulse, plateauing at the maximal fluorescence (F-max).

I propose doing a couple straightforward things with the entire snapshot.

1. Calculate the fluorescence response curve using the time intervals calculated from the `*rawData0101.bin` file and the maximum (or other summary statistic) metric from each frame.
2. Use the F-dark, F-min, and F-max images to calculate the Fv/Fm values that are used to measure the efficiency of PSII (F-variable = F-max - F-min) for each (plant) pixel.
3. Store the Fv/Fm image, the histogram of values, and other summary statistics.

How we collect the data is a whole other issue. I suspect we should not do this using the standard row-scan method because I suspect the light pulse over one area will expose neighboring plants, and dark adaptation is required before imaging. Maybe a randomized sampling approach could be used?

Here is a really rough sketch out of some code that does a lot of what I listed above: https://github.com/nfahlgren/shared_jupyter_notebooks/blob/master/terraref/psII_analysis_demo.ipynb

**Comment by dlebauer** [comment]
@nfahlgren that sounds good for a first pass.

It sounds like you are going to identify three images (dark, min, max) based on an average over all pixesl and the compute Fv/Fm. This would probably be a good first order estimate of Fv/Fm for each pixel. 

If it is possible and biologically relevant that different pixels will reach max/min at different time points. I would propose to get better per-pixel estimates for Fv/Fm:
* put all images together in a cube with dimensions x, y, time
* compute Fv/Fm for each x,y pair

**Comment by nfahlgren** [comment]
@dlebauer good question, not sure about the biological significance of the response curve for different parts of the plant, but makes sense that it could differ.

**Comment by ZongyangLi** [comment]
@dlebauer Just for a double check.

Is this extractor work for creating 101 pngs and 101 geotiffs(or 101 rasters in one geotiff file) for a sub-directory's raw data. Also create a text file for 'timestamp value'?

**Comment by dlebauer** [comment]
@ZongyangLi I will let @nfahlgren answer your question; I think the idea of a png is for thumbnails; in this case it might make more sense to have a movie than thumbnails. 

@nfahlgren Would it make sense to either make a movie or a netcdf file with dimensions x, y, t? Or, should we convert each to tiff, find the dark, min, and max, and discard the rest?

**Comment by dlebauer** [comment]
@nfahlgren Two issues to address and one other thought

* [ ] how much does the result depend on distance to sensor?
* [ ] one scientist* raised the concern that the light is not strong enough to saturate the photosynthetic machinery - 
  * Maybe this is a concern for physiological measurements, but less important for phenotyping where the differences are more important.
  * *I can track down the source for further information

**on calculating appropriate values** 

Here are three options for computing Fv/Fm, though there are many possible variations on these. 

1. as is now:
  * find the dark, min, and max, and discard the rest of the images?
  * use mean from each image to compute Fv/Fm
2. make a movie (eg a netcdf file with dimensions x, y, t)
   * then find Fv/Fm for each pixel, where these may not be in sync across pixels
   * then report the Fv/Fm for each pixel, or summarize as the 95th quantile
3. Find 5% of pixels with max(Fmax) and then subset these from each of the images in a stack, and compute Fv/Fm 

When using quantiles prior to canopy closure we may need to first do a mask or truncate all non-responsive pixels.

**Comment by rachelshekar** [comment]
Still need more information how to get traits from this camera, what is the further goal for PSII data.
Still working with Noah on how to process the data 
-Zongyang

**Comment by ZongyangLi** [comment]
Some gif files created by a set of PSII raw data:
https://drive.google.com/open?id=0B5QCp_Onc6nOSW41Z3kzU0VQak0

**Comment by rachelshekar** [comment]
code from noah
https://github.com/nfahlgren/shared_jupyter_notebooks/blob/master/terraref/psII_analysis_demo.ipynb

**Comment by rachelshekar** [comment]
Notes from phone meeting https://github.com/terraref/computing-pipeline/issues/216

**Comment by rachelshekar** [comment]
@ZongyangLi - did you get the information you needed from Noah to start on this?

**Comment by ZongyangLi** [comment]
Yes, planning to create 2 extractors for this:
1. bin files converter
2. Fv/Fm pseudocolored image and histogram

**Comment by max-zilla** [comment]
@ZongyangLi extractor is ready here:
https://github.com/terraref/extractors-multispectral/tree/master/psii

I ended up combining your two extractors into one: convert 101 files to PNG, then generate image and histogram. Once @jdmaloney has the mount to Roger NFS ready (should be quick) I can get this running.
