### ISSUE TITLE
Factor out geospatial meta-data extraction into a single extractor that downstream code will depend on

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#159]
### Description

The step(s) of converting from the lemnatec-provided metadata to a (to be determined) common reference system currently appears to be done in many different algorithms.

Once we do have a canonical set of reference points (https://github.com/terraref/reference-data/issues/32) on the field scanner field, having only one place that does the conversion will make this easier.
### TODO
- [x] create the geospatial extractor ( #101) that stores geospatial metadata in Clowder
- [x] Identify code that contains duplicated logic, make sure the best bits are in the geospatial extractor above
- [ ] Then refactor existing code to use data from the Clowder PostGIS database.

**Comment by max-zilla** [comment]
This is going into the terrautils library:
https://github.com/terraref/terrautils

I've already done synthesis of existing geospatial code into one place - last remaining issue is to get plot definitons from BETY as discussed here:
https://github.com/terraref/computing-pipeline/issues/307

Will close this issue so that issue can reflect last remaining task.
