### ISSUE TITLE
Reorganize and /scripts folder and make consistent use of script names, README files, tests, etc

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#160]
### Description

Clean up and add consistent naming and contents to the [scripts folder](https://github.com/terraref/computing-pipeline/tree/master/scripts). This will make it clear where to find reusable components and reduce duplication of effort.

[Here is a list of sensors and extractors currently under development](https://docs.google.com/spreadsheets/d/1LLiQSFHbEWoo_FkvG1nl-XoSq_lZ_o6VazfxmPfOH9Y/edit#gid=0).

Some of the existing scripts have reusable components, for example code that converts from gantry coordinates to geospatial coordinates (#159 deals with refactoring these and using the geospatial directory that exists in the [geostreams_extractor branch](https://github.com/terraref/computing-pipeline/tree/geostreams_extractor/scripts/geospatial). Similarly, the hyperspectral data code contains code for parsing Environmental data, of which a subset (the sky-facing hyperspectral radiometer) is required to process the hyperspectral data. These should moved to a separate folder named 'environment' which would/could also contain data for the lightning and irrigation data streams.
### TODO
- [ ] reorganize folders
- [ ] apply standard naming to scripts (e.g. rename `terraref.*` to `hyperspectral.*`. These should use names that are consistent with and indicate the extractor names, the data sources, (and perhaps the data levels?) @craig-willis?
  - [ ] @craig-willis please propose some names in the [spreadsheet](https://docs.google.com/spreadsheets/d/1LLiQSFHbEWoo_FkvG1nl-XoSq_lZ_o6VazfxmPfOH9Y/edit#gid=0).
- [ ] add other **_required_** files, including 
  - README
  - test.sh along with test inputs and outputs  
  - any others?
  - Extractor script, docker file?
### Further Suggestions / Request for Feedback

Please review the above proposal, and suggest changes. Especially @craig-willis, @max-zilla, @robkooper, and anyone else developing code within the @terraref/developers  group.

**Comment by max-zilla** [comment]
This is a nice writeup. 

You guys can growl at me if you don't like this idea, I thought it would be a good way to make more evident what extractors might share code/algorithms and how they could interact with one another.

**Comment by czender** [comment]
cz's proposed renaming of hyperspectral files. @FlyingWithJerome improvements welcome.
CalculationWorks.py -> unsure (consolidate into others?)
DataProcess.py -> obsolete (delete)
EnvironmentalLoggerAnalyser.py -> environmental_logger_json2netcdf.py
EnvironmentalLoggerUnitTest.py -> environmental_logger_unittest.py
JsonDealer.py -> hyperspectral_metadata.py
dummy.nc -> hyperspectral_dummy.nc
pixel2Geographic.py -> unsure (consolidate? inherit?)
terraref.nco -> hyperspectral_calibration.nco
terraref.sh* -> hyperspectral_workflow.sh

**Comment by dlebauer** [comment]
Thanks @czender 

Would it be onerous to move the environmental_logger files to their own directory and isolate their functionality for example by replacing their use in the hyperspectral workflow and just expect that the environmental data is available?

**Comment by FlyingWithJerome** [comment]
@dlebauer I agree. Since environmental_logger is now an independent workflow, it would be good to have their own directory and isolate their functionality. 
@czender CalculationWorks.py and pixel2Geographic.py are files to do calculation, and the reason they are separated from main scripts is that we can easily review their algorithms (e.g., coordinate transforming) and constant values (e.g., flx_sns array, camera_positon). I would recommend to merge these two files and name the new file as "hyperspectral_algorithm.py" or "hyperspectral_calculation.py"

**Comment by czender** [comment]
@FlyingWithJerome @dlebauer 
those names seems fine to me. if others are ok with them we can segregate environmental logger into its own directory. maybe after thursday telecon to make sure names are ok.

**Comment by czender** [comment]
I renamed most files in hyperspectral directory as described above. @FlyingWithJerome please finish the job by combining/consolidating CalculationWorks.py and pixel2Geographic.py into a file like we discussed. Once this all works from one directory, well move environmental logger scripts into their own directory.

**Comment by FlyingWithJerome** [comment]
@czender Yes, I will

**Comment by max-zilla** [comment]
I will give an update on the call today, but I spoke with @robkooper and @dlebauer about structuring going forward, and how we probably can't have this repo be the main discussion for all these different extractors forever as it's already fairly busy.

So we're making some gradual changes to emphasize this repo as focused on the pipeline portion itself:
- scripts and tools to prepare raw data before transfer
- components necessary for transfer from MAC/Danforth/KSU/etc. to NCSA
- logging and monitoring components for pipeline health/reporting

The extractors and algorithms can gradually move to separate repositories based on type of scanner. This will allow us to focus issues + wikis + etc. there instead of juggling everything here. I've started by making 3 with extractors we are preparing to deploy:
- https://github.com/terraref/extractors-lemnatec-indoor (e.g. PlantCV)
- https://github.com/terraref/extractors-environmental (e.g. enviro logger)
- https://github.com/terraref/extractors-stereo-rgb (e.g. demosaic, field stitching)
I also took the opportunity to flesh out the READMEs a bit.

Eventually we'll probably want:
- extractors-hyperspectral (e.g. SWIR, VNIR)
- extractors-multispectral (e.g. NDVI, cropCircle active reflectance)'
- extractors-flourescence (e.g. PSII)
- extractors-thermal (e.g. FLIRIR)
Maybe we can merge some of these depending on how much activity we anticipate.

**Comment by craig-willis** [comment]
@rachelshekar @max-zilla 
I'm assigned to this ticket, but not clear what my role is.

**Comment by rachelshekar** [comment]
@dlebauer - who should be working on this? It's a huge task.

**Comment by max-zilla** [comment]
@craig-willis @rachelshekar I created this originally. Craig we can discuss on Tuesday.

**Comment by craig-willis** [comment]
Discussed with Max and this is complete. Closing.
