### ISSUE TITLE
Hyperspectral Calibration

### ISSUE THREAD

**Issue by solmazhajmohammadi** [terraref/computing-pipeline#208]
Meeting notes from 2016/11/16 
Charlie Zender: 
" Reflectances are too high when white counts are close to dark counts (denominator is small) and/or exposure (numerator) is large. White reference calibration standard is suspect. Dark counts look reasonable. White reference is uneven, possibly too low in UV and NIR."
Here is the examples from @czender 
![rfl_img_max](https://cloud.githubusercontent.com/assets/17046539/20804793/e6172ff6-b7b9-11e6-94de-65d9acd6205f.png)

![rfl_img_max_scl](https://cloud.githubusercontent.com/assets/17046539/20804802/e98bf0c2-b7b9-11e6-963a-3427e11f0513.png)

**Comment by solmazhajmohammadi** [comment]
Here is the data I got from  2016/10/21 using 20ms exposure time at 2:58PM:
![ref](https://cloud.githubusercontent.com/assets/17046539/20805189/5f59e97a-b7bb-11e6-8249-004fbf48682e.jpg)
@czender can you please let me know the exact timestamp, so I can look at the same data that you used to plot your data.

**Comment by solmazhajmohammadi** [comment]
@czender , Do you have spectralon target in the FOV when you are processing your data? If spectralon target is in your region of interest, so this will explain why you are getting these data. Please let me know exactly which data you are looking at.
your white reference is the average of the pixels in the spectralon target. So in your calibrated data, you might see values greater than one, when your numerator is greater than denominator. simply when your nominator is coming from spectralon panel.

**Comment by solmazhajmohammadi** [comment]
@remotesensinglab Continuing the discussion from Google doc in here:
I have used the average of dark image and subtracted the value. I didn’t  see the behaviour in my dataset.

**Comment by czender** [comment]
I suggest that when the HS extractor is running, we all look at the same output file...

**Comment by max-zilla** [comment]
@jterstriep and I will prioritize this sensor/output ASAP.

**Comment by czender** [comment]
@solmazhajmohammadi 
Also tagging @FlyingWithJerome and @hmb1 and @dlebauer 
Please examine the file:
`/projects/arpae/terraref/sites/ua-mac/Level_1/hyperspectral/2016-11-14/2016-11-14__12-02-00-886/3bc4bd12-ff75-4cac-bb25-ac1f444c0423_.nc
`
The variables containing the minimum and maximum reflectances for all
wavelengths are rfl_img_max and rfl_img_min. Reflectance values range
up to the high 20's. 

For concreteness, I selected the 664nm band (chlorophyll A) with
`ncks -O -d wavelength,0.664e-6 /projects/arpae/terraref/sites/ua-mac/Level_1/hyperspectral/2016-11-14/2016-11-14__12-02-00-886/3bc4bd12-ff75-4cac-bb25-ac1f444c0423_.nc ~/chla_664nm_20161114_1202.nc
`
Its reflectance peaks at a modest 1.13. I hyperslabbed the first 3200
scanlines with 
`ncks -O -d y,,3200 ~/chla_664nm_20161114_1202.nc ~/chla_664nm_20161114_1202_sqr.nc
`
The resulting image is [here](http://dust.ess.uci.edu/tmp/chla_664nm.png)
It shows areas where the reflectance exceeds 1.0.

Does your calibration procedure yield similar/identical results?
Looking forward to hearing what you find.

Charlie

**Comment by dlebauer** [comment]
If you are asking whether values > 1 for reflectance at 664 nm is sensible, perhaps @remotesensinglab can help. I do know that the chlorophyll a fluoresces so the signal will contain both reflected energy from 664 and energy absorbed from other bands and re-emitted in 664. [This review](https://academic.oup.com/jxb/article/51/345/659/652534/Chlorophyll-fluorescence-a-practical-guide#11239099) suggests the signal can be 1-2% of energy absorbed, and if all of this is emitted in a narrow band I suspect that the signal can be quite strong.

Wasit @remotesensinglab is more familiar with the Solar-Induced Fluorescence metric. Wasit - what are meaningful reflectances in the 664 band?

**Comment by czender** [comment]
SIF is much smaller than the biases between our reflectances and reality. I don't think SIF significantly affects the representativeness of 664nm as an indicator of the calibration quality.
But it's fine if someone wants to use a different wavelength for comparison.

**Comment by dlebauer** [comment]
Yep I was wrong. Here is a good reference https://files.gitter.im/PecanProject/pecan/PEcAn_RTM/oyQf/Campbell_Middleton_Corp_kim_2008_STE.pdf

**Comment by czender** [comment]
This issue should remain open pending the resolution of the VNIR calibration exercise proposed four items above.

**Comment by dlebauer** [comment]
Sorry I didn't mean to close

**Comment by remotesensinglab** [comment]
All,
I looked at the image and spectra. I agree that it is not an issue related to SIF. SIF emission peaks are at 687-689 nm and 740 nm. Reflectances at these wavelengths should not be over 1 as well.  I also looked at another image (8afea01b-03de-4d80-a3d9-49afec5dfa26_.nc_588c96f44f0c06726ada5059), and think that there is overexposure on this image which is evident at 575 nm. 
![119spectra_plot jpg](https://cloud.githubusercontent.com/assets/22847312/22607735/c340d9ae-ea1e-11e6-9b06-409da21e887e.png)

**Comment by remotesensinglab** [comment]
I will look other images and see if I find other indicators of the issue. I tend to agree Solmaz' assessment that these areas over 1 might be coming from the white reference panels.

**Comment by solmazhajmohammadi** [comment]
@czender The data is collected with 45ms exposure time. With this exposure time, spectralon target is saturated. Please check a dataset that has been collected with 25 or 20ms exposure time.

**Comment by remotesensinglab** [comment]
That is a good point Solmaz. The data collected with 45ms exposure time may be overexposed, which may be why the reflectance is higher than 1 for some bright targets.

**Comment by czender** [comment]
@solmazhajmohammadi @dlebauer as you can see with
`ncks -v xps_img_wht calibration_vnir_45ms.nc`
the maximum count measured is ~56000 out of ~64000 possible counts. 
1. So why do you say 45ms saturates the spectralon target?
2. If you think 45ms saturates the target, why were images as recently as December being exposed with that duration? We need to never oversaturate the exposure.

**Comment by solmazhajmohammadi** [comment]
1. I see the maximum count for white target is 57351 with 45ms exposure time. However if you plot the data in 3D, you will see a clear cut which shows that  data is saturated. (I'll look into it to see why the maximum value in not 2^16. ) 
Anyway, the max in white target and sample data both is 57351. So you may see some values >1 when you are using the average value over the white reference. 

2.  I dont think that we are running any scan with 45ms anymore. 11/14 was during the FAT and system was running 24hours. Probably some random scripts was running during that 10 days. you can even find a hyperspectral scan that is done in middle of the night.

**Comment by remotesensinglab** [comment]
@czender,
I recall we evaluated the data with exposure time back in November or early December, and found that there are some level of saturation when exposure time is over 25ms. On the figure above, I suspect that the significant drop of reflectance at 575 nm is due to overexposure of this data.

**Comment by dlebauer** [comment]
summary of discussion from today, for discussion next Tuesday:

1. [ ] Stop collecting data w/ exposure > 25ms; 
    * [ ] remove overexposed images from 2016; 
2. [ ] Get a new white reflectance standard ordered / installed (20-40%) to increase dynamic range of exposures. (currently calibrated to 95%)
    * we currently have 4%, 50% 
3. [ ] Do calibration for multiple zenith angles; 
   * currently only have single calibration for Oct 2016
   * need systematic recalibration for all exposure times under 25ms; get white reflectance at every 10 degrees of zenith angle.
4. [ ] interpolate or simulate SWIR for VNIR

**Comment by FlyingWithJerome** [comment]
@dlebauer @czender 
I would like to know if the data from Environmental Sensor is available (I know it had been deployed). If we have the real-time calibration data things would be much easier.

If calibration for multiple zenith angles is for compensating the SZA difference in one single scanline, won't 10 degrees be too big?

For the dynamic range of exposures, won't we need the data between 95% - 50 %?

**Comment by czender** [comment]
@FlyingWithJerome and @hmb1 there will be a HS calibration telecon tues. noon pacific time at https://meet.illinois.edu/shekar/SN3T1Z79
please join if possible

on roger environmental sensor extractor places data at 
/projects/arpae/terraref/sites/ua-mac/Level_1/EnvironmentLogger/

@dlebauer please point to this issue the person interested in calibration on yesterday's phone conf., and who's name sounded to me like "wahid" or "wahib". The hyperspectral_calibration.nco script shows, in the header, where to go for further documentation. All HS workflow people should do likewise with their scripts. Of particular relevance for Tuesday's meeting are:
  https://docs.google.com/document/d/1w_zHHlrPVKsy1mnW9wrVzAU2edVqZH8i1IZa5BZxVpo/edit#heading=h.jjfbhbos05cc # Calibration employed since 20160908
https://github.com/terraref/computing-pipeline/issues/88 # Calibration employed until 20160908, i.e., old (flux-based) method

**Comment by dlebauer** [comment]
Sorry I thought I had properly introduced you to Wasit / @remotesensinglab

**Comment by rachelshekar** [comment]
@smarshall-bmr - can you give an update on this?  It is necessary to complete task #281

**Comment by dlebauer** [comment]
@smarshall-bmr what we need is the diurnal images in #263

**Comment by dlebauer** [comment]
@czender is this epic a duplicate of epic #281 (develop new calibration procedure) & can they be merged?

**Comment by dlebauer** [comment]
<img width="886" alt="screen shot 2017-03-16 at 11 38 25 am" src="https://cloud.githubusercontent.com/assets/464871/24007646/4016aaa6-0a3d-11e7-89e3-ab59a249693b.png">

**Comment by czender** [comment]
@smarshall-bmr because these Spectralon images will be used for calibration, it is important to take them under conditions that are as geometrically simple ( and thus reproducible ) as possible. Ideally you would provide images at a complete set of zenith angles on (at least) two days: one completely clear sky data and one completely overcast day. Any clouds increase the likelihood that shadows or side-scattering will contaminate the calibration (and eventually lead to inaccurate derived reflectances).

**Comment by czender** [comment]
@dlebauer this issue is a hodgepodge that has converged mostly on a subset of #281 that is best described by #289. So it could be merged with #289 (or visa versa).

**Comment by czender** [comment]
I don't know how to "merge" issues but this should be merged with #289.

**Comment by rachelshekar** [comment]
@czender - I added it to the epic.  Looks like this issue can be closed.

**Comment by dlebauer** [comment]
follow up in #289.
