### ISSUE TITLE
Updates to standardize LAS format / metadata

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#257]
LAS files should follow OGC las 1.4 standard  
* specification: https://www.asprs.org/committee-general/laser-las-file-format-exchange-activities.html
* relevant article https://rapidlasso.com/2016/01/10/create-proper-las-1-4-files-with-lastools-for-free/
* Follow a similar convention to meteorology and hyperspectral use of CF naming conventions where applicable and consistent w/ standard
* also use geojson polygon representation of bounding box

Goal is for (raster, point cloud) files to differ where it is useful, but have similar interfaces where applicable.

Are all x,y,z units in m relative to the gantry origin?

### Completion Criteria   

* [x] standard format defined
* [x] added to extractor
* [ ] old las files updated

**Comment by max-zilla** [comment]
@solmazhajmohammadi we can follow up about this - we should be able to implement this to existing extractor.

**Comment by rachelshekar** [comment]
@solmazhajmohammadi - please provide an update/next steps

**Comment by solmazhajmohammadi** [comment]
Bounding box representation depends on  [Issue 44](https://github.com/terraref/reference-data/issues/44)

**Comment by dlebauer** [comment]
What about the other metadata? Have you looked into the OGC specifications?

**Comment by rachelshekar** [comment]
@solmazhajmohammadi can this be closed?

**Comment by rachelshekar** [comment]
@solmazhajmohammadi  - @max-zilla needs to know if anything needs to be changed with extractor before the code freeze on Aug 15

**Comment by solmazhajmohammadi** [comment]
The LAS files are in standard format as long as we are using the PDAL version >1.3
double checked with Max, we are using version 1.5
However, the ply files are still in pointcloud origin. I have updated the issue [44](https://github.com/terraref/reference-data/issues/44), in order to do the transformation. 
This would georeference the LAS files.
