### ISSUE TITLE
Determine how to support webpages created by collaborators

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#276]
For example: 

* full field interactive mosaic by @ZongyangLi and @pless 
* interactive gwas by @zhenbinHU and @gpmorrisksu 
* summary of data in BETYdb by @nickheyek 

## TODO:

* [ ] add steps for deploying static + dynamic web apps to documentation
* [ ] consider re-organizing (perhaps all websites should be under terraref/www)?

See also #295

**Comment by dlebauer** [comment]
Static pages can be served from https://terraref.ncsa.illinois.edu/webapps/ua-mac/. Presumably any extractor can write out a page to  to  terraref/sites/ua-mac/www/ on ROGER and then the website will be available.

@nickheyek generated a dynamic app (updated daily) that is being served here: http://141.142.211.143:5000/ (how is this different? what is required to post this?)

## TODO:

* [ ] add steps for deploying static + dynamic web apps to documentation
* [ ] consider re-organizing (perhaps all websites should be under terraref/www)?

**Comment by robkooper** [comment]
@dlebauer the webapp from @nickheyek needs to be served under a different name (traitvis for example) and we can have http://terraref.ncsa.illinois.edu/traitvis point to this. The other options is give each of these a seperate URL (i.e. traitvis.terraref.org).

**Comment by rachelshekar** [comment]
@robkooper said these can be supported on the new website using Bootstrap

**Comment by robkooper** [comment]
More specific, we can make them styled looking like the rest of webpages if we use something like bootstrap to get a theme (also clowder in that case), but we can always do this if we have something that contains a header and a footer, and place in the body where we can insert the actual webpage.

**Comment by rachelshekar** [comment]
shiny app https://terraref.shinyapps.io/traitvis/

**Comment by dlebauer** [comment]
we have a nice protocol for deploying webapps as docker images on workbench, e.g. traitvis.workbench.terraref.org

Given a dockerfile, the deployment process can be handled by our team on a case-by-case basis
