### ISSUE TITLE
Process data from the Danforth Center LemnaTec system from 2016/2017

### ISSUE THREAD

**Issue by nfahlgren** [terraref/computing-pipeline#335]
### Description (REQUIRED)

This epic defines the steps required to upload, process, store, etc. data from phenotyping experiments done at the Danforth Center on the indoor LemnaTec system. The data upload and extractor systems are in place already but will need to be updated to be more flexible for handling changes in the experimental design of each dataset.

**Available datasets**:

- TM015
- TM016
- TM017
- TM018
- TM021
- TM022
- TM023
- TM024
 
Experimental metadata is currently stored in an ad hoc format in spreadsheets and word processor documents. Sensor metadata is stored in a structured format.

### Completion Criteria (REQUIRED/ESSENTIAL)

This may not be a completely comprehensive list of steps, but issues will be opened for each of the individual components.

- [ ] Convert experimental metadata to a standardized format
  - [ ] Add experimental metadata to BETYdb (see https://github.com/terraref/reference-data/issues/137)
  - [ ] Metadata will be added to Clowder during upload also
- [ ] Develop PlantCV processing code for each of the experiment/sensor configurations
  - [ ] Add new PlantCV code to the LemnaTec-indoor extractor (https://github.com/terraref/extractors-lemnatec-indoor)
  - [ ] Extractor will choose which method to run based on metadata
- [ ] We may need to update the set of traits added to BETYdb

**Comment by nfahlgren** [comment]
@dlebauer I closed this because I accidentally created it as an issue instead of an epic. The epic/issue is #336

**Comment by dlebauer** [comment]
OK I'll re-close

Note that the epic button in the right panel gives the option to convert any issue to an epic (it is the first option):

![image](https://user-images.githubusercontent.com/464871/27204876-4728788a-51f3-11e7-94a5-53cbfad4d976.png)
