### ISSUE TITLE
Update pipeline for changes with flirIRCamera

### ISSUE THREAD

**Issue by jdemieville-ua** [terraref/computing-pipeline#610]
### Description 
Thermal camera (flirIRCamera) relocated to new external frame and enclosure. As part of this change, there are adjustments to the physical position of the sensor as noted in fixed metadata and new calibration coefficients that must be applied to account for the new window. Additional adjustment of instrument may occur. Note that the new x-position is negative. The camera has been moved south of the reference position.
![20200603_134419](https://user-images.githubusercontent.com/40777832/83696457-6590bc00-a5b1-11ea-8f48-c35b984cf8ea.jpg)

Old fixed metadata offsets are as follows:
`        <entry7 type="KeyValueUnitTriple">
            <Key type="String" value="location in camera box x" />
            <Value type="String" value="0.346" />
            <Unit type="String" value="m" />
        </entry7>
        <entry8 type="KeyValueUnitTriple">
            <Key type="String" value="location in camera box y" />
            <Value type="String" value="2.250" />
            <Unit type="String" value="m" />
        </entry8>
        <entry9 type="KeyValueUnitTriple">
            <Key type="String" value="location in camera box z" />
            <Value type="String" value="0.520" />
            <Unit type="String" value="m" />
        </entry9>`

New fixed metadata offsets are as follows:
`        <entry7 type="KeyValueUnitTriple">
            <Key type="String" value="location in camera box x" />
            <Value type="String" value="-1.035" />
            <Unit type="String" value="m" />
        </entry7>
        <entry8 type="KeyValueUnitTriple">
            <Key type="String" value="location in camera box y" />
            <Value type="String" value="1.684" />
            <Unit type="String" value="m" />
        </entry8>
        <entry9 type="KeyValueUnitTriple">
            <Key type="String" value="location in camera box z" />
            <Value type="String" value="0.856" />
            <Unit type="String" value="m" />
        </entry9>`

### Tasks Remaining for @jdemieville-ua 

- [ ] Compute calibration coefficients from data collected April/May 2020 with new enclosure

- [ ] Implement changes in gantry operating scripts

### Completion Criteria for pipeline implementation

- [ ] Update fixed metadata for flirIRcamera

- [ ] Update calibration for flirIRcamera

**Comment by jdemieville-ua** [comment]
Changes to offsets implemented in gantry operating scripts. Raw data and MATLAB script still need made available.


### Tasks Remaining for @jdemieville-ua 

- [x] Compute calibration coefficients from data collected April/May 2020 with new enclosure

- [ ] Implement changes in gantry operating scripts

- [ ] Make raw data and MATLAB script available


### Completion Criteria for pipeline implementation

- [ ] Update fixed metadata for flirIRcamera

- [ ] Update calibration for flirIRcamera

**Comment by jdemieville-ua** [comment]
Raw data and MATLAB script used for generating coefficients is available at [https://drive.google.com/file/d/10rtqYVvH_JhVYMtgxZYk_aRJU7uwPN15/view?usp=sharing](url)


### Tasks Remaining for @jdemieville-ua 

- [x] Compute calibration coefficients from data collected April/May 2020 with new enclosure

- [x] Implement changes in gantry operating scripts

- [x] Make raw data and MATLAB script available


### Completion Criteria for pipeline implementation

- [ ] Update fixed metadata for flirIRcamera

- [ ] Update calibration for flirIRcamera
